project_name: blackfriday-steam
builds:
  - id: md2steam
    main: ./cmd/md2steam
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
